### ISSUE TITLE
项目启动失败: Error 1146: Table 'gin_web.tb_sys_user' doesn't exist

### ISSUE THREAD

**Issue by guanbinbin** [piupuer/gin-web#1]
本地运行时，autoMigrate无法自动建表，提示：项目启动失败: Error 1146: Table 'gin_web.tb_sys_user' doesn't exist。
请问如何解决？

**Comment by piupuer** [comment]
能把错误信息堆栈发一下吗，我没有出现过类似错误哟

**Comment by piupuer** [comment]
如果是mysql5.x无法启动可参考https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

**Comment by guanbinbin** [comment]
谢谢解答~
