### ISSUE TITLE
invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Aquarius-M** [piupuer/gin-web#14]
初学者，麻烦大佬给看一下是什么问题

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/47274897/140290132-826eca95-1bcd-4fa8-8984-f213ff82d870.png">

**Comment by piupuer** [comment]
空指针异常，目前最新分支有bug，请先使用tag v1.1.7

**Comment by piupuer** [comment]
请更新最新tag v1.2.1
