### ISSUE TITLE
failed: exec: \"mysqldump

### ISSUE THREAD

**Issue by yjyyjy777** [piupuer/gin-web#16]
time="2022-03-25T22:44:40+08:00" level=error msg="[gin-web]project run failed: exec: \"mysqldump\": executable file not found in %PATH%\nstack: goroutine 1 [running]:\nruntime/debug.Stack()\n\tC:/Program Files/Go/src/runtime/debug/stack.go:24

**Comment by piupuer** [comment]
感谢来信，但您所发的用户不在服务区，请稍后再发！

**Comment by piupuer** [comment]
Please check if your local env has “mysqldump”, this tool is usually installed with “mysql”.
