### ISSUE TITLE
这个怎么处理

### ISSUE THREAD

**Issue by wiiler** [piupuer/gin-web#2]
![image](https://user-images.githubusercontent.com/9715482/84849430-d5aa4200-b087-11ea-8e8a-80124ec6be17.png)

**Comment by piupuer** [comment]
应该是读取到空数据，redis中不存在指定用户信息，有可能是数据同步问题，也有可能你没有初始化数据。
1. 首先看下数据库是有有数据，没有数据，把conf目录下config.dev.yml中system => init-data设置为true，重启下项目
2. 有数据看下mysql与redis数据是否一致
目前redis存的表数据以表名称+json格式存的，比如读取user表，执行redis命令：get gin_web_tb_sys_user => json str， 你到网上找下json转换工具，看下数据是否与mysql一致。如果不一致可以清理下redis缓存，按照步骤1重启项目
