### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by sunhailin-Leo** [piupuer/gin-web#5]
* 如果不使用 `docker` 而使用 `go build -o main` 的话，打包出来的二进制，放到服务器的时候读取配置文件的路径还是本地打包的配置的绝对路径。想问下怎么解决？如果单独部署二进制文件的话。

**Comment by piupuer** [comment]
由于使用到packr打包工具，构建main文件前需要执行packr build才能将配置目录打包到二进制中

你可以在这里下载https://github.com/gobuffalo/packr/releases/tag/v2.8.0
参考https://github.com/gobuffalo/packr/blob/v2.8.0/v2/README.md#building-a-binary

如果本地go.mod下载好依赖，也可以直接用命令构建
``` shell
cd $GOPATH/pkg/mod/github.com/gobuffalo/packr/v2@v2.8.0/packr2 && go build && chmod +x packr2
cd your_project_path
$GOPATH/pkg/mod/github.com/gobuffalo/packr/v2@v2.8.0/packr2/packr2 build

# 接下来构建你自己的应用
go build -o main
```
参考https://github.com/piupuer/gin-web/blob/master/Dockerfile#L30

后续如果还有问题可以在QQ群联系我，主页有二维码
