### ISSUE TITLE
小问题：启用redis时登录失败

### ISSUE THREAD

**Issue by ccfish86** [piupuer/gin-web#6]
use-redis: true时，登录失败，好像是Redis没有初始化数据。

**Comment by ccfish86** [comment]
另外 端口：10000 被 百度网盘占用了，导致无法使用127.0.0.1:10000调用接口（这个困扰了我一段时间），
![image](https://user-images.githubusercontent.com/15622514/92839872-0560b000-f413-11ea-9f06-0cdf75c98b7e.png)

**Comment by piupuer** [comment]
### redis无法同步数据

1. 检查redis是否开启，连接地址是否正常
2. 检查mysql是否开启binlog日志同步
``` sql
show variables like 'log_bin';
```
3. 检查错误日志输出

**Comment by piupuer** [comment]
### 端口占用
1. [修改后端配置](https://github.com/piupuer/gin-web/blob/v1.0.0/conf/config.dev.yml#L6)

2. 前端
- [直接改api地址](https://github.com/piupuer/gin-web-vue/blob/master/.env.development#L2)
- 如果用了nginx直接修改反向代理端口即可
