### ISSUE TITLE
大佬 登录接口502了

### ISSUE THREAD

**Issue by nullF** [piupuer/gin-web#8]
大佬 登录接口502了

**Comment by piupuer** [comment]
这是nginx错误，请检查nginx配置，和本项目无关哦






------------------ 原始邮件 ------------------
发件人: nullF <notifications@github.com&gt;
发送时间: 2020年11月30日 21:52
收件人: piupuer/gin-web <gin-web@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[piupuer/gin-web] 大佬 登录接口502了 (#8)





 
大佬 登录接口502了

**Comment by nullF** [comment]
演示网站的登录接口502了，请大佬查看一波------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;piupuer&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年11月30日(星期一) 晚上10:34
收件人:&nbsp;&quot;piupuer/gin-web&quot;<gin-web@noreply.github.com&gt;;
抄送:&nbsp;&quot;nullF&quot;<895941139@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [piupuer/gin-web] 大佬 登录接口502了 (#8)

**Comment by piupuer** [comment]
恢复正常
